from . import diceast as ast
from .enums import *
from .errors import *
from .roll import RollResult
from .roll.stringifier import Stringifier

def parse(expr: str | ast.Expression) -> ast.Expression: ...
def roll(
    expr: str | ast.Expression, stringifier: Stringifier | None = None, advantage: Advantage = ...
) -> RollResult: ...
def seed(s: int | float | str | bytes | bytearray | None = None) -> None: ...
