import random
from typing import Any

import numpy.random
from _typeshed import Incomplete

__all__ = ["random_impl"]

SeedT = int | float | str | bytes | bytearray

class NumpyRandom(random.Random):
    def __init__(self, bitgen_type: type[numpy.random.BitGenerator], x: SeedT | None = None) -> None: ...
    def random(self) -> float: ...
    def getrandbits(self, k: int) -> int: ...
    def randbytes(self, n: int) -> bytes: ...
    def seed(self, a: SeedT | None = None, version: int = 2) -> None: ...
    def getstate(self) -> tuple[Any, ...]: ...
    def setstate(self, state: Any) -> None: ...

random_impl: Incomplete
